background #1a110f
foreground #f1dfda
cursor #ffb4a2
selection_background #ffb4a2
color0 #1a110f
color1 #ffb4ab
color2 #dac58d
color4 #ffb4a2
active_border_color #ffb4a2
inactive_border_color #a08c88
