theme[main_bg]="#1a110f"
theme[main_fg]="#f1dfda"
theme[title]="#ffb4a2"
theme[hi_fg]="#ffb4a2"
theme[selected_bg]="#ffb4a2"
theme[selected_fg]="#1a110f"
theme[inactive_fg]="#a08c88"
theme[graph_text]="#f1dfda"
theme[proc_misc]="#dac58d"
theme[cpu_box]="#a08c88"
theme[mem_box]="#a08c88"
theme[net_box]="#a08c88"
theme[proc_box]="#a08c88"
theme[div_line]="#a08c88"

theme[temp_start]="#dac58d"
theme[temp_mid]="#ffb4a2"
theme[temp_end]="#ffb4ab"

theme[cpu_start]="#dac58d"
theme[cpu_mid]="#ffb4a2"
theme[cpu_end]="#ffb4ab"

theme[free_start]="#dac58d"
theme[free_mid]="#ffb4a2"
theme[free_end]="#ffb4a2"

theme[cached_start]="#a08c88"
theme[cached_mid]="#ffb4a2"
theme[cached_end]="#ffb4a2"

theme[available_start]="#dac58d"
theme[available_mid]="#ffb4a2"
theme[available_end]="#ffb4a2"

theme[used_start]="#ffb4a2"
theme[used_mid]="#ffb4ab"
theme[used_end]="#ffb4ab"

theme[download_start]="#dac58d"
theme[download_mid]="#ffb4a2"
theme[download_end]="#ffb4a2"

theme[upload_start]="#dac58d"
theme[upload_mid]="#ffb4a2"
theme[upload_end]="#ffb4a2"

theme[process_start]="#dac58d"
theme[process_mid]="#ffb4a2"
theme[process_end]="#ffb4a2"

theme[graph_low]="#1a110f"
theme[graph_high]="#ffb4a2"

theme[meter_bg]="#a08c88"
