theme[main_bg]="{{colors.background.default.hex}}"
theme[main_fg]="{{colors.on_background.default.hex}}"
theme[title]="{{colors.primary.default.hex}}"
theme[hi_fg]="{{colors.primary.default.hex}}"
theme[selected_bg]="{{colors.primary.default.hex}}"
theme[selected_fg]="{{colors.background.default.hex}}"
theme[inactive_fg]="{{colors.outline.default.hex}}"
theme[graph_text]="{{colors.on_background.default.hex}}"
theme[proc_misc]="{{colors.tertiary.default.hex}}"
theme[cpu_box]="{{colors.outline.default.hex}}"
theme[mem_box]="{{colors.outline.default.hex}}"
theme[net_box]="{{colors.outline.default.hex}}"
theme[proc_box]="{{colors.outline.default.hex}}"
theme[div_line]="{{colors.outline.default.hex}}"

theme[temp_start]="{{colors.tertiary.default.hex}}"
theme[temp_mid]="{{colors.primary.default.hex}}"
theme[temp_end]="{{colors.error.default.hex}}"

theme[cpu_start]="{{colors.tertiary.default.hex}}"
theme[cpu_mid]="{{colors.primary.default.hex}}"
theme[cpu_end]="{{colors.error.default.hex}}"

theme[free_start]="{{colors.tertiary.default.hex}}"
theme[free_mid]="{{colors.primary.default.hex}}"
theme[free_end]="{{colors.primary.default.hex}}"

theme[cached_start]="{{colors.outline.default.hex}}"
theme[cached_mid]="{{colors.primary.default.hex}}"
theme[cached_end]="{{colors.primary.default.hex}}"

theme[available_start]="{{colors.tertiary.default.hex}}"
theme[available_mid]="{{colors.primary.default.hex}}"
theme[available_end]="{{colors.primary.default.hex}}"

theme[used_start]="{{colors.primary.default.hex}}"
theme[used_mid]="{{colors.error.default.hex}}"
theme[used_end]="{{colors.error.default.hex}}"

theme[download_start]="{{colors.tertiary.default.hex}}"
theme[download_mid]="{{colors.primary.default.hex}}"
theme[download_end]="{{colors.primary.default.hex}}"

theme[upload_start]="{{colors.tertiary.default.hex}}"
theme[upload_mid]="{{colors.primary.default.hex}}"
theme[upload_end]="{{colors.primary.default.hex}}"

theme[process_start]="{{colors.tertiary.default.hex}}"
theme[process_mid]="{{colors.primary.default.hex}}"
theme[process_end]="{{colors.primary.default.hex}}"

theme[graph_low]="{{colors.background.default.hex}}"
theme[graph_high]="{{colors.primary.default.hex}}"

theme[meter_bg]="{{colors.outline.default.hex}}"
