background {{colors.background.default.hex}}
foreground {{colors.on_background.default.hex}}
cursor {{colors.primary.default.hex}}
selection_background {{colors.primary.default.hex}}
color0 {{colors.surface.default.hex}}
color1 {{colors.error.default.hex}}
color2 {{colors.tertiary.default.hex}}
color4 {{colors.primary.default.hex}}
active_border_color {{colors.primary.default.hex}}
inactive_border_color {{colors.outline.default.hex}}
